version: "3"
services:
  gitlab:
    build:
      context: "./gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url '${GITLAB_DOMAIN_NAME}'\nredis['enable'] = false\nnginx['listen_https'] = false\nnginx['listen_port'] = 80\nnginx['custom_gitlab_server_config'] = \"set_real_ip_from 172.0.0.0/8;\\nreal_ip_header X-Real-IP;\\nreal_ip_recursive on;\"\npostgresql['enable'] = false\ngitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']\ngitlab_rails['redis_host'] = 'redis'\ngitlab_rails['redis_database'] = 8\ngitlab_rails['db_host'] = '${GITLAB_POSTGRES_HOST}'\ngitlab_rails['db_username'] = '${GITLAB_POSTGRES_USER}'\ngitlab_rails['db_password'] = '${GITLAB_POSTGRES_PASSWORD}'\ngitlab_rails['db_database'] = '${GITLAB_POSTGRES_DB}'\ngitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'\ngitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_HOST_SSH_PORT}\n"
    volumes:
      - "${DATA_PATH_HOST}/gitlab/config:/etc/gitlab"
      - "${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab"
      - "${GITLAB_HOST_LOG_PATH}:/var/log/gitlab"
    ports:
      - "${GITLAB_HOST_HTTP_PORT}:80"
      - "${GITLAB_HOST_HTTPS_PORT}:443"
      - "${GITLAB_HOST_SSH_PORT}:22"
    depends_on:
      - "redis"
      - "postgres"
  redis:
    build: "./redis"
    volumes:
      - "${DATA_PATH_HOST}/redis:/data"
    ports:
      - "${REDIS_PORT}:6379"
  postgres:
    build:
      context: "./postgres"
      args:
        - "POSTGRES_VERSION=${POSTGRES_VERSION}"
    volumes:
      - "${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data"
      - "${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}"
      - "GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}"
      - "GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}"
      - "GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}"
      - "JUPYTERHUB_POSTGRES_INIT=${JUPYTERHUB_POSTGRES_INIT}"
      - "JUPYTERHUB_POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}"
      - "JUPYTERHUB_POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}"
      - "JUPYTERHUB_POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}"
      - "SONARQUBE_POSTGRES_INIT=${SONARQUBE_POSTGRES_INIT}"
      - "SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}"
      - "SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}"
      - "SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}"
      - "POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}"
      - "POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}"
      - "POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}"
      - "POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}"
volumes: {}
